version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...  
      - docker build -t md-text-recognition .
      - docker tag md-text-recognition:latest 970556883193.dkr.ecr.us-east-1.amazonaws.com/md-text-recognition:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 970556883193.dkr.ecr.us-east-1.amazonaws.com/md-text-recognition:latest